version: '2'
services:
    demojhipster2-app:
        image: demojhipster2
        external_links:
            - demojhipster2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demojhipster2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demojhipster2-mysql:
        extends:
            file: mysql.yml
            service: demojhipster2-mysql
